platform :ios, '15.0'

use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'sanhak_2' do
  config = use_native_modules!

  # Firebase 관련 Pods 추가
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Auth', :modular_headers => true
  pod 'Firebase/Database', :modular_headers => true

  # React Native 설정
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false,
  )

  # 테스트 타겟
  target 'sanhak_2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # post_install 단계에서 Flipper 설정 추가
  post_install do |installer|
    react_native_post_install(installer)
    # Flipper 초기화가 필요하면 아래 주석을 풀어서 사용
    # flipper_post_install(installer)
    # 배포 대상 경고 무시 설정 추가
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0' # 경고를 무시할 배포 대상 설정
      end
    end

    # 중복 파일 경고 무시
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' # 시뮬레이터에서 arm64 빌드 제외
    end
  end
end