platform :ios, '15.0'
use_frameworks! :linkage => :dynamic  # 동적 프레임워크로 빌드

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'sanhak_2' do
  config = use_native_modules!

  # Firebase 관련 Pods (모듈 헤더 지정 없이도 됨)
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
  )

  post_install do |installer|
    react_native_post_install(installer)
  
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-video'
        target.build_configurations.each do |config|
          other_ldflags = config.build_settings['OTHER_LDFLAGS'] || ['$(inherited)']
  
          # 1) 이미 -ObjC 추가해봤으니, 추가로 -force_load 적용
          unless other_ldflags.any? { |f| f.include?('-force_load') }
            # 예시: React-Core
            other_ldflags << '-force_load Pods/React-Core/libReact-Core.a'
            
            # 또는 실제 라이브러리 경로/이름이 조금 다를 수 있으니 확인 필요
            # ex) other_ldflags << '-force_load Pods/React-RCTEventDispatcher/libReact-RCTEventDispatcher.a'
          end
  
          config.build_settings['OTHER_LDFLAGS'] = other_ldflags
        end
      end
    end
  end
end
