// src\screens\kit\kit_guide_2\styles.js
import {StyleSheet, Dimensions} from 'react-native';
import theme from '../../../theme'; // 개발 규칙: 폰트 적용
const scaleWidth = Dimensions.get('screen').width / 390; // 개발 규칙: 상대 크기 적용
const scaleHeight = Dimensions.get('screen').height / 844; // 개발 규칙: 상대 크기 적용

const styles = StyleSheet.create({
  video: {
    width: '100%',
    height: 200,
    bottom: 58,
  },
  container: {
    display: 'flex',
    width: 390 * scaleWidth,
    height: 844 * scaleHeight,
    flexDirection: 'column',
    alignItems: 'center',
    flexWrap: 'nowrap',
    backgroundColor: '#ffffff',
    position: 'relative',
    overflow: 'hidden',
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  },
  header: {
    display: 'flex',
    height: 68 * scaleHeight,
    paddingTop: 24 * scaleHeight,
    paddingRight: 24 * scaleWidth,
    paddingBottom: 24 * scaleHeight,
    paddingLeft: 24 * scaleWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
  },
  headerIcon: {
    width: 20 * scaleWidth,
    height: 20 * scaleWidth,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 1,
  },
  headerTitle: {
    height: 20 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 16 * scaleWidth,
    fontWeight: '600',
    lineHeight: 20 * scaleHeight,
    color: '#000000',
    position: 'relative',
    textAlign: 'left',
    zIndex: 2,
  },
  headerRightIconContainer: {
    display: 'flex',
    width: 20 * scaleWidth,
    flexDirection: 'row',
    gap: 8 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 3,
  },
  headerRightIcon: {
    width: 20 * scaleWidth,
    height: 20 * scaleWidth,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 4,
  },
  banner: {
    display: 'flex',
    height: 280 * scaleHeight,
    paddingTop: 58 * scaleHeight,
    paddingRight: 78 * scaleWidth,
    paddingBottom: 58 * scaleHeight,
    paddingLeft: 78 * scaleWidth,
    gap: 10 * scaleHeight,
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: '#e1e4ef',
    position: 'relative',
    overflow: 'hidden',
    zIndex: 5,
  },
  bannerInner: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 6,
  },
  bannerBackgroundImage: {
    width: 397 * scaleWidth,
    height: 112 * scaleHeight,
    flexShrink: 0,
    position: 'absolute',
    top: -13 * scaleHeight,
    left: -85 * scaleWidth,
    zIndex: 7,
  },
  bannerForegroundImage: {
    width: 60 * scaleWidth,
    height: 30 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    zIndex: 8,
  },
  bannerText: {
    display: 'flex',
    width: 140.571 * scaleWidth,
    height: 83.429 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 70 * scaleWidth,
    fontWeight: '400',
    lineHeight: 83.429 * scaleHeight,
    color: '#ffffff',
    position: 'relative',
    textAlign: 'center',
    zIndex: 9,
  },
  progressBar: {
    display: 'flex',
    width: 365 * scaleWidth,
    height: 45 * scaleHeight,
    paddingTop: 12 * scaleHeight,
    paddingRight: 13 * scaleWidth,
    paddingBottom: 12 * scaleHeight,
    paddingLeft: 13 * scaleWidth,
    flexDirection: 'row',
    gap: 10 * scaleWidth,
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: 'rgba(93, 93, 98, 0.32)',
    borderTopLeftRadius: 13 * scaleWidth,
    borderTopRightRadius: 13 * scaleWidth,
    borderBottomRightRadius: 13 * scaleWidth,
    borderBottomLeftRadius: 13 * scaleWidth,
    position: 'relative',
    zIndex: 10,
  },
  progressBarIcon: {
    width: 20 * scaleWidth,
    height: 20 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 11,
  },
  progressBarIconImage: {
    width: 16.667 * scaleWidth,
    height: 16.667 * scaleHeight,
    position: 'relative',
    zIndex: 12,
    marginTop: 1.667 * scaleHeight,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 1.667 * scaleWidth,
  },
  progressBarText: {
    height: 17 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 14 * scaleWidth,
    fontWeight: '400',
    lineHeight: 16.707 * scaleHeight,
    color: '#ffffff',
    position: 'relative',
    textAlign: 'left',
    zIndex: 13,
  },
  progressBarTrack: {
    width: 173 * scaleWidth,
    height: 8 * scaleHeight,
    flexShrink: 0,
    backgroundColor: 'rgba(126, 133, 150, 0.2)',
    borderTopLeftRadius: 8 * scaleWidth,
    borderTopRightRadius: 8 * scaleWidth,
    borderBottomRightRadius: 8 * scaleWidth,
    borderBottomLeftRadius: 8 * scaleWidth,
    position: 'relative',
    zIndex: 14,
  },
  progressBarPlayIcon: {
    width: 28 * scaleWidth,
    height: 28 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 16,
  },
  progressBarPlayIconImage: {
    width: 19.25 * scaleWidth,
    height: 19.25 * scaleHeight,
    position: 'relative',
    zIndex: 17,
    marginTop: 4.375 * scaleHeight,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 4.375 * scaleWidth,
  },
  instructions: {
    display: 'flex',
    paddingTop: 40 * scaleHeight,
    paddingRight: 24 * scaleWidth,
    paddingBottom: 40 * scaleHeight,
    paddingLeft: 24 * scaleWidth,
    gap: 20 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 18,
  },
  instruction: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 19,
  },
  instructionIconContainer: {
    display: 'flex',
    width: 24 * scaleWidth,
    height: 24 * scaleHeight,
    paddingTop: 2 * scaleHeight,
    paddingRight: 6 * scaleWidth,
    paddingBottom: 2 * scaleHeight,
    paddingLeft: 6 * scaleWidth,
    gap: 10 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: '#7595ff',
    borderTopLeftRadius: 12 * scaleWidth,
    borderTopRightRadius: 12 * scaleWidth,
    borderBottomRightRadius: 12 * scaleWidth,
    borderBottomLeftRadius: 12 * scaleWidth,
    position: 'relative',
    zIndex: 20,
  },
  instructionIconText: {
    ...theme.fonts.Medium,
    height: 20 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 14 * scaleWidth,
    lineHeight: 20 * scaleHeight,
    color: '#ffffff',
    position: 'relative',
    textAlign: 'left',
    zIndex: 21,
  },
  instructionText: {
    ...theme.fonts.Medium,
    height: 20 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 14 * scaleWidth,
    fontWeight: '500',
    lineHeight: 20 * scaleHeight,
    color: '#353535',
    position: 'relative',
    textAlign: 'left',
    zIndex: 22,
  },
  captureButton: {
    display: 'flex',
    width: 211 * scaleWidth,
    paddingTop: 12 * scaleHeight,
    paddingRight: 50 * scaleWidth,
    paddingBottom: 12 * scaleHeight,
    paddingLeft: 50 * scaleWidth,
    flexDirection: 'row',
    gap: 10 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: '#7595ff',
    borderTopLeftRadius: 48 * scaleWidth,
    borderTopRightRadius: 48 * scaleWidth,
    borderBottomRightRadius: 48 * scaleWidth,
    borderBottomLeftRadius: 48 * scaleWidth,
    position: 'relative',
    zIndex: 43,
  },
  captureButtonTextContainer: {
    width: 111 * scaleWidth,
    height: 18 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    zIndex: 44,
  },
  captureButtonIcon: {
    width: 18 * scaleWidth,
    height: 18 * scaleHeight,
    position: 'absolute',
    top: 0,
    left: 93 * scaleWidth,
    overflow: 'hidden',
    zIndex: 46,
  },
  captureButtonText: {
    ...theme.fonts.Bold,
    display: 'flex',
    width: 112 * scaleWidth,
    height: 18 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 14 * scaleWidth,
    lineHeight: 18 * scaleHeight,
    color: '#ffffff',
    letterSpacing: 0.56 * scaleWidth,
    position: 'absolute',
    top: 2 * scaleHeight,
    left: 0,
    textAlign: 'center',
    textTransform: 'uppercase',
    zIndex: 45,
  },
  spacer: {
    height: 110 * scaleHeight,
    alignSelf: 'stretch',
    flexShrink: 0,
    backgroundColor: '#ffffff',
    position: 'relative',
    zIndex: 47,
  },
  footerImage: {
    width: 148 * scaleWidth,
    height: 5 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    zIndex: 49,
  },
});

export default styles;
