import {StyleSheet, Dimensions} from 'react-native';
import theme from '../../../theme'; // 개발 규칙: 폰트 적용
const scaleWidth = Dimensions.get('screen').width / 390; // 개발 규칙: 상대 크기 적용
const scaleHeight = Dimensions.get('screen').height / 844; // 개발 규칙: 상대 크기 적용

const styles = StyleSheet.create({
  video: {
    width: '100%',
    height: 200 * scaleHeight,
    bottom: 58,
  },
  container: {
    display: 'flex',
    width: 390 * scaleWidth,
    height: 844 * scaleHeight,
    flexDirection: 'column',
    alignItems: 'center',
    flexWrap: 'nowrap',
    backgroundColor: theme.colors.White,
    position: 'relative',
    overflow: 'hidden',
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  },
  header: {
    display: 'flex',
    height: 68 * scaleHeight,
    paddingTop: 24 * scaleHeight,
    paddingRight: 24 * scaleWidth,
    paddingBottom: 24 * scaleHeight,
    paddingLeft: 24 * scaleWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
  },
  headerIcon: {
    width: 20 * scaleWidth,
    height: 20 * scaleWidth,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 1,
  },
  headerTitle: {
    height: 20 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 16 * scaleWidth,
    lineHeight: 20 * scaleHeight,
    color: theme.colors.Black,
    position: 'relative',
    textAlign: 'left',
    zIndex: 2,
    ...theme.fonts.Medium,
  },
  headerRightIconContainer: {
    display: 'flex',
    width: 20 * scaleWidth,
    flexDirection: 'row',
    gap: 8 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 3,
  },
  headerRightIcon: {
    width: 20 * scaleWidth,
    height: 20 * scaleWidth,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 4,
  },
  banner: {
    display: 'flex',
    height: 280 * scaleHeight,
    paddingTop: 58 * scaleHeight,
    paddingRight: 78 * scaleWidth,
    paddingBottom: 58 * scaleHeight,
    paddingLeft: 78 * scaleWidth,
    gap: 10 * scaleHeight,
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: theme.colors.lightBlue,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 5,
  },
  bannerInner: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 6,
  },
  bannerBackgroundImage: {
    width: 397 * scaleWidth,
    height: 112 * scaleHeight,
    flexShrink: 0,
    position: 'absolute',
    top: -13 * scaleHeight,
    left: -85 * scaleWidth,
    zIndex: 7,
  },
  bannerForegroundImage: {
    width: 60 * scaleWidth,
    height: 30 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    zIndex: 8,
  },
  bannerText: {
    display: 'flex',
    width: 140.571 * scaleWidth,
    height: 83.429 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 70 * scaleWidth,
    lineHeight: 83.429 * scaleHeight,
    color: theme.colors.White,
    position: 'relative',
    textAlign: 'center',
    zIndex: 9,
    ...theme.fonts.Bold,
  },
  progressBar: {
    display: 'flex',
    width: 365 * scaleWidth,
    height: 45 * scaleHeight,
    paddingTop: 12 * scaleHeight,
    paddingRight: 13 * scaleWidth,
    paddingBottom: 12 * scaleHeight,
    paddingLeft: 13 * scaleWidth,
    flexDirection: 'row',
    gap: 10 * scaleWidth,
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: 'rgba(93, 93, 98, 0.32)',
    borderRadius: 13 * scaleWidth,
    position: 'relative',
    zIndex: 10,
  },
  progressBarText: {
    height: 17 * scaleHeight,
    flexShrink: 0,
    flexBasis: 'auto',
    fontSize: 14 * scaleWidth,
    lineHeight: 16.707 * scaleHeight,
    color: theme.colors.White,
    position: 'relative',
    textAlign: 'left',
    zIndex: 13,
    ...theme.fonts.Regular,
  },
  progressBarTrack: {
    width: 173 * scaleWidth,
    height: 8 * scaleHeight,
    flexShrink: 0,
    backgroundColor: theme.colors.lightGray,
    borderRadius: 8 * scaleWidth,
    position: 'relative',
    zIndex: 14,
  },
  progressBarPlayIcon: {
    width: 28 * scaleWidth,
    height: 28 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 16,
  },
  progressBarPlayIconImage: {
    width: 19.25 * scaleWidth,
    height: 19.25 * scaleHeight,
    position: 'relative',
    zIndex: 17,
    marginTop: 4.375 * scaleHeight,
    marginLeft: 4.375 * scaleWidth,
  },
  instructions: {
    display: 'flex',
    paddingTop: 40 * scaleHeight,
    paddingHorizontal: 24 * scaleWidth,
    gap: 20 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 18,
  },
  instruction: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 19,
  },
  instructionIconContainer: {
    display: 'flex',
    width: 24 * scaleWidth,
    height: 24 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: theme.colors.mainBlue,
    borderRadius: 12 * scaleWidth,
    position: 'relative',
    zIndex: 20,
  },
  instructionIconText: {
    height: 20 * scaleHeight,
    flexShrink: 0,
    fontSize: 14 * scaleWidth,
    lineHeight: 20 * scaleHeight,
    color: theme.colors.White,
    position: 'relative',
    textAlign: 'left',
    zIndex: 21,
    ...theme.fonts.Medium,
  },
  instructionText: {
    height: 20 * scaleHeight,
    flexShrink: 0,
    fontSize: 14 * scaleWidth,
    lineHeight: 20 * scaleHeight,
    color: theme.colors.textGray,
    position: 'relative',
    textAlign: 'left',
    zIndex: 22,
    ...theme.fonts.Regular,
  },
  captureButton: {
    display: 'flex',
    width: 211 * scaleWidth,
    paddingVertical: 12 * scaleHeight,
    paddingHorizontal: 50 * scaleWidth,
    flexDirection: 'row',
    gap: 10 * scaleWidth,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    backgroundColor: theme.colors.mainBlue,
    borderRadius: 48 * scaleWidth,
    position: 'relative',
    zIndex: 43,
    top: 30 * scaleHeight,
  },
  captureButtonText: {
    display: 'flex',
    width: 112 * scaleWidth,
    height: 18 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 14 * scaleWidth,
    lineHeight: 18 * scaleHeight,
    color: theme.colors.White,
    textAlign: 'center',
    textTransform: 'uppercase',
    zIndex: 45,
    ...theme.fonts.Bold,
  },
  spacer: {
    height: 110 * scaleHeight,
    alignSelf: 'stretch',
    flexShrink: 0,
    backgroundColor: theme.colors.White,
    position: 'relative',
    zIndex: 47,
  },
  footerImage: {
    width: 148 * scaleWidth,
    height: 5 * scaleHeight,
    flexShrink: 0,
    position: 'relative',
    zIndex: 49,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  instructions: {
    display: 'flex',
    paddingTop: 40 * scaleHeight,
    paddingHorizontal: 24 * scaleWidth,
    gap: 20 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  instructionBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12 * scaleWidth,
    backgroundColor: theme.colors.lightGray,
    padding: 10 * scaleHeight,
    borderRadius: 10 * scaleWidth,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  iconContainer: {
    width: 30 * scaleWidth,
    height: 30 * scaleHeight,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.White,
    borderRadius: 20 * scaleWidth,
  },
  instructionText: {
    flex: 1,
    fontSize: 14 * scaleWidth,
    color: theme.colors.textGray,
    textAlign: 'left',
    ...theme.fonts.Regular,
  },
});

export default styles;
