name: Build React Native App

on:
  push:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 5. Android 빌드
      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleRelease

      # 6. APK 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          
  ios-build:
    runs-on: macos-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. CocoaPods 설치
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 5. iOS 프로젝트 준비
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      # 6. iOS 빌드
      - name: Print Working Directory
        run: echo $PWD

      - name: Build iOS App
        env:
          XCODE_WORKSPACE: ios/sanhak_2.xcworkspace  # 워크스페이스 이름 (변경 필요)
          XCODE_SCHEME: sanhak_2                    # 스킴 이름 (변경 필요)
        run: |
          xcodebuild \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/sanhak_2.xcarchive \
            archive

      # 7. IPA 업로드
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app-release-ipa
          path: ios/build/sanhak_2.xcarchive
