name: Test React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Jest 테스트 실행 (공통 로직 테스트)
      - name: Run Jest tests
        run: npm test

  android-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. 의존성 설치
      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install
          cd android
          ./gradlew clean

      # 5. Android 테스트 실행
      - name: Run Android Tests
        run: |
          cd android
          ./gradlew test --stacktrace

  ios-test:
    runs-on: macos-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. Install CocoaPods
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      # 4. Install Dependencies
      - name: Install Dependencies
        run: |
          npm install
          cd ios
          pod install

      # 5. Run iOS Tests
      - name: Run iOS Tests
        env:
          XCODE_WORKSPACE: ios/sanhak_2.xcworkspace
          XCODE_SCHEME: sanhak_2
        run: |
          xcodebuild \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGNING_ALLOWED=NO \
            test
