name: Build React Native App

on:
  push:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # 3. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 5. Android 빌드
      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleRelease

      # 6. APK 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

  ios-build:
    runs-on: macos-latest
  
    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
  
      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
  
      # 3. CocoaPods 설치
      - name: Install CocoaPods
        run: sudo gem install cocoapods
  
      # 4. 의존성 설치
      - name: Install Node.js dependencies
        run: npm install
  
      # 5. iOS 의존성 준비
      - name: Prepare iOS Dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --verbose
  
      # 6. Xcode 버전 설정
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
  
      # 7. Derived Data(캐시) 제거
      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
  
      # 8. iOS 빌드
      - name: Build iOS App
        env:
          XCODE_WORKSPACE: ios/sanhak_2.xcworkspace
          XCODE_SCHEME: sanhak_2
        run: |
          xcodebuild \
            -workspace $XCODE_WORKSPACE \ 
            -scheme $XCODE_SCHEME \
            -configuration Debug \  
            -sdk iphonesimulator \           
            -destination 'generic/platform=iOS Simulator' \
            clean build              
