name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1' # 필요한 Node.js 버전 지정

    # 3. 의존성 설치
    - name: Install dependencies
      run: npm install

    # 4. 테스트 실행
    - name: Run tests
      run: npm test

    # 5. 애플리케이션 빌드
    - name: Build application
      run: npm run build
